# fly.toml file generated for public-blog on 2023-02-04T13:08:18+02:00

app = "public-blog"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "ghost:5.33.6"

[env]
  url = "https://public-blog.fly.dev" 
  database__client = "sqlite3"  
  database__connection__filename = "content/data/ghost.db"  
  database__useNullAsDefault = "true"  
  database__debug = "false"

[mounts]
  source="data"
  destination="/var/lib/ghost/content"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 2368
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
