[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]


[[redirects]]
from = "/blog/*"
to = "https://public-blog.fly.dev/:splat"
status = 200
force = true
headers = {X-Forwarded-Host = "https://lively-cajeta-2c3459.netlify.app"}

[[redirects]]
from = "/blog"
to = "https://public-blog.fly.dev/blog/"
status = 200
force = true
headers = {X-Forwarded-Host = "https://lively-cajeta-2c3459.netlify.app"}